import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Menu from "@/components/ui/menu";
import Intro from "@/components/ui/intro";
import Links from "@/components/ui/links";
import Projects from "@/components/ui/project";
import Footer from "@/components/ui/footer";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Marlon Schafranski - Links Uteis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br"  className="bg-gradient-to-b from-blue-700 to-gray-950" >

      <body
      className={inter.className}>
        {children}
        <Menu />
        <Intro />
        <Links />
        <Projects />
        <Footer />
      </body>
    </html>
  );
}
